version: 2

sources:
  - name: nypd_raw_data
    database: dbtdb # Tell dbt to look for the source in the "raw" database
    schema: dbt_raw_data # You wouldn't put your source data in public, would you?
    tables:
      - name: awards
      - name: allegations
      - name: penalties
      - name: officers
      - name: lawsuits
