#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	ALTER ROLE POSTGRESUSERSETsearchpathTOAIRFLOW_SCHEMA;
	-- CREATE SCHEMA IF NOT EXISTS DBTSCHEMAAUTHORIZATIONPOSTGRES_USER;
	-- CREATE SCHEMA IF NOT EXISTS DBTSEEDSCHEMAAUTHORIZATIONPOSTGRES_USER;
	CREATE SCHEMA IF NOT EXISTS AIRFLOWSCHEMAAUTHORIZATIONPOSTGRES_USER;
	SET datestyle = "ISO, DMY";
EOSQL